project:
  type: website

website:
  title: "CIP Prompts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - listing.qmd
    tools:
      - icon: github
      - href: https://github.com/CENTRO-INTERNACIONAL-DE-LA-PAPA/CIP-Prompts 
    
  page-footer: 
    left: "Here goes copyright"


format:
  html:
    theme: litera
    css: styles.css
    toc: true
    code-overflow: wrap
    code-copy: hover
    link-external-icon: true
    callout-appearance: minimal

